version: '2'
services:
  mm-int:
    build: .
    environment:
      FLASK_DEBUG: 1
      MATTERMOST_WEBHOOK_URLS: '"https://mattermost.dynamictivity.com/hooks/xesfsu9pj3no8emqagi7yuo6jr", "mm-int-github"'
    ports:
        - "5000:5000"
